### ISSUE TITLE
Update for Summer 2020-2021 Springboard

### ISSUE THREAD

**Issue by morganjwilliams** [core-skills/03-zero-to-data-science#1]
We'll need to update a few things for the next iteration of the springboard, including:
- [x] The runsheet and timings (both in AEST and AWST).
- [x] The Binder link has a typo - we'll need to update this and check that Binder launches as expected.
- [x] Clearing out old material which is unused currently.
- [x] Checking the environment file.

**Comment by grongier** [comment]
I just checked the environment file and explicitly added pip to eliminate a warning from conda, and managed to run the two notebooks without trouble.

**Comment by morganjwilliams** [comment]
For the environment file (and others coming up) we might want to look at changing the names to reflect the day rather than week naming; we could probably also cull some of the superfluous packages for this one (only really need basic matplotlib + pandas from memory).

**Comment by grongier** [comment]
You're right that would be better, I'll have a look this afternoon.

**Comment by morganjwilliams** [comment]
Will be looking to test some of these environments against the participants internal package repositories - where relevant we should specify some minimum version requirements to check where issues might pop up (e.g. to make sure we have some of the newer features of `matplotlib`, `pandas`).

**Comment by morganjwilliams** [comment]
As suspected may occur, the environment creation ran into a HTTP error associated with the internal network; we'll work to address this for the coming weeks.
